# Path configuration
export PATH=$HOME/.local/bin:/usr/local/bin:$PATH

# Force colour support
export TERM=xterm-256color

# Detect OS platform once
export MACOS=$([ "$(uname)" = "Darwin" ] && echo true || echo false)
export LINUX=$([ "$MACOS" = "false" ] && echo true || echo false)

# Add platform-specific paths
if [[ "$MACOS" == true ]]; then
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
    export PATH=$PATH:/Users/dariusgrassi/.spicetify
fi

# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Define possible plugin locations (first found will be used)
p10k_locations=(
    "/opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme"  # Only keep homebrew for macOS
    "$HOME/.zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme"
)

syn_highlight_locations=(
    "/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"  # Only keep homebrew for macOS
    "$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
)

# Source Powerlevel10k theme (first found location)
for location in "${p10k_locations[@]}"; do
    if [[ -f "$location" ]]; then
        source "$location"
        break
    fi
done

# Source syntax highlighting (first found location)
for location in "${syn_highlight_locations[@]}"; do
    if [[ -f "$location" ]]; then
        source "$location"
        break
    fi
done

# Load personal Powerlevel10k configuration
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Vi mode settings
bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^F' history-incremental-search-forward

# Completion system setup
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select
bindkey '^[[Z' reverse-menu-complete

# Auto-activate and deactivate venv for dirs containing one
autoload -U add-zsh-hook
function auto_venv_manage() {
  if [[ -n "$VIRTUAL_ENV" && ! -f ".venv/bin/activate" ]]; then
    deactivate
  elif [[ -z "$VIRTUAL_ENV" && -f ".venv/bin/activate" ]]; then
    source .venv/bin/activate
  fi
}
add-zsh-hook chpwd auto_venv_manage
auto_venv_manage  # run on shell start

# Common aliases
alias ls='ls --color=auto -l'
alias python='python3'
alias cp='cp -v'
alias rm='rm -i'
alias vim='nvim'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias gst='git status'
alias gca='git commit -a'
